import { QueryInterface, Sequelize } from 'sequelize';

export = {
	up: async (queryInterface: QueryInterface, sequelize: Sequelize) => {
		await queryInterface.bulkInsert('country', [
			{
				country: 'Denmark',
				iso: 'DK',
				country_code: 'DK',
				telephone_code: '45',
				currency_id: '1',
				vat: '25',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country: 'Sweden',
				iso: 'SE',
				country_code: 'SE',
				telephone_code: '46',
				currency_id: '2',
				vat: '25',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country: 'Norway',
				iso: 'NO',
				country_code: 'NO',
				telephone_code: '47',
				currency_id: '4',
				vat: '25',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country: 'Andorra',
				iso: 'CH',
				country_code: 'AD',
				telephone_code: '376',
				currency_id: '3',
				vat: '0',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country: 'Albania',
				iso: 'CH',
				country_code: 'AL',
				telephone_code: '355',
				currency_id: '3',
				vat: '0',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country: 'Austria',
				iso: 'CH',
				country_code: 'AT',
				telephone_code: '43',
				currency_id: '3',
				vat: '25',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country: 'Bosnia and Herzegovina',
				iso: 'CH',
				country_code: 'BA',
				telephone_code: '387',
				currency_id: '3',
				vat: '0',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country: 'Belgium',
				iso: 'CH',
				country_code: 'BE',
				telephone_code: '32',
				currency_id: '3',
				vat: '20',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country: 'Bulgaria',
				iso: 'CH',
				country_code: 'BG',
				telephone_code: '359',
				currency_id: '3',
				vat: '20',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country: 'Switzerland',
				iso: 'CH',
				country_code: 'CH',
				telephone_code: '41',
				currency_id: '3',
				vat: '20',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country: 'Cyprus',
				iso: 'CH',
				country_code: 'CY',
				telephone_code: '357',
				currency_id: '3',
				vat: '20',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country: 'Czech Republic',
				iso: 'CH',
				country_code: 'CZ',
				telephone_code: '420',
				currency_id: '3',
				vat: '25',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country: 'Estonia',
				iso: 'CH',
				country_code: 'EE',
				telephone_code: '372',
				currency_id: '3',
				vat: '25',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country: 'Spain',
				iso: 'CH',
				country_code: 'ES',
				telephone_code: '34',
				currency_id: '3',
				vat: '25',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country: 'Finland',
				iso: 'CH',
				country_code: 'FI',
				telephone_code: '358',
				currency_id: '3',
				vat: '25',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country: 'France',
				iso: 'CH',
				country_code: 'FR',
				telephone_code: '33',
				currency_id: '3',
				vat: '25',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country: 'Greece',
				iso: 'CH',
				country_code: 'GR',
				telephone_code: '30',
				currency_id: '3',
				vat: '25',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country: 'Croatia',
				iso: 'CH',
				country_code: 'HR',
				telephone_code: '385',
				currency_id: '3',
				vat: '25',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country: 'Hungary',
				iso: 'CH',
				country_code: 'HU',
				telephone_code: '36',
				currency_id: '3',
				vat: '25',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country: 'Iceland',
				iso: 'CH',
				country_code: 'IE',
				telephone_code: '354',
				currency_id: '3',
				vat: '0',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country: 'Italy',
				iso: 'CH',
				country_code: 'IT',
				telephone_code: '39',
				currency_id: '3',
				vat: '25',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country: 'Liechtenstein',
				iso: 'CH',
				country_code: 'LI',
				telephone_code: '423',
				currency_id: '3',
				vat: '25',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country: 'Lithuania',
				iso: 'CH',
				country_code: 'LT',
				telephone_code: '370',
				currency_id: '3',
				vat: '25',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country: 'Luxembourg',
				iso: 'CH',
				country_code: 'LU',
				telephone_code: '352',
				currency_id: '3',
				vat: '25',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country: 'Latvia',
				iso: 'CH',
				country_code: 'LV',
				telephone_code: '371',
				currency_id: '3',
				vat: '25',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country: 'Monaco',
				iso: 'CH',
				country_code: 'MC',
				telephone_code: '377',
				currency_id: '3',
				vat: '25',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country: 'Macedonia',
				iso: 'CH',
				country_code: 'MK',
				telephone_code: '389',
				currency_id: '3',
				vat: '25',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country: 'Netherlands',
				iso: 'NL',
				country_code: 'NL',
				telephone_code: '31',
				currency_id: '3',
				vat: '25',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country: 'Poland',
				iso: 'CH',
				country_code: 'PL',
				telephone_code: '48',
				currency_id: '3',
				vat: '25',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country: 'Portugal',
				iso: 'CH',
				country_code: 'PT',
				telephone_code: '351',
				currency_id: '3',
				vat: '25',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country: 'Romania',
				iso: 'CH',
				country_code: 'RO',
				telephone_code: '40',
				currency_id: '3',
				vat: '25',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country: 'Russia',
				iso: 'CH',
				country_code: 'RU',
				telephone_code: '7',
				currency_id: '3',
				vat: '0',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country: 'Saudi Arabia',
				iso: 'CH',
				country_code: 'SA',
				telephone_code: '966',
				currency_id: '3',
				vat: '0',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country: 'Slovenia',
				iso: 'CH',
				country_code: 'SI',
				telephone_code: '386',
				currency_id: '3',
				vat: '25',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country: 'Slovakia',
				iso: 'CH',
				country_code: 'SK',
				telephone_code: '421',
				currency_id: '3',
				vat: '25',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country: 'Turkey',
				iso: 'CH',
				country_code: 'TR',
				telephone_code: '90',
				currency_id: '3',
				vat: '0',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country: 'Ukraine',
				iso: 'CH',
				country_code: 'UA',
				telephone_code: '380',
				currency_id: '3',
				vat: '0',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country: 'United Kingdom',
				iso: 'UK',
				country_code: 'UK',
				telephone_code: '44',
				currency_id: '5',
				vat: '20',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country: 'Germany',
				iso: 'DE',
				country_code: 'DE',
				telephone_code: '49',
				currency_id: '3',
				vat: '19',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country: 'Ireland',
				iso: 'CH',
				country_code: 'IE',
				telephone_code: '353',
				currency_id: '3',
				vat: '0',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country: 'Mauritius',
				iso: 'CH',
				country_code: 'MU',
				telephone_code: '230',
				currency_id: '3',
				vat: '25',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country: 'Greenland',
				iso: 'CH',
				country_code: 'GL',
				telephone_code: '299',
				currency_id: '3',
				vat: '0',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country: 'Afghanistan',
				iso: 'CH',
				country_code: 'AF',
				telephone_code: '93',
				currency_id: '3',
				vat: '20',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country: 'Georgia',
				iso: 'CH',
				country_code: 'GE',
				telephone_code: '995',
				currency_id: '3',
				vat: '0',
				created_at: new Date(),
				updated_at: new Date(),
			},

		]);
	},

	down: async (queryInterface: QueryInterface, sequelize: Sequelize) => {
		await queryInterface.bulkDelete('country', null, {});
	}
};
