import { QueryInterface, Sequelize } from 'sequelize';

export = {
	up: async (queryInterface: QueryInterface, sequelize: Sequelize) => {
		await queryInterface.bulkInsert('shipment_price', [
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				max_zipcode: '3699',
				min_zipcode: '1000',
				min_running: 0,
				max_running: 0.19,
				price: 700,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '3700',
				max_zipcode: '3999',
				min_running: 0,
				max_running: 0.19,
				price: 2440,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '4000',
				max_zipcode: '4799',
				min_running: 0,
				max_running: 0.19,
				price: 720,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '4800',
				max_zipcode: '4999',
				min_running: 0,
				max_running: 0.19,
				price: 790,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '5000',
				max_zipcode: '5999',
				min_running: 0,
				max_running: 0.19,
				price: 840,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '6000',
				max_zipcode: '7399',
				min_running: 0,
				max_running: 0.19,
				price: 910,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '7400',
				max_zipcode: '8999',
				min_running: 0,
				max_running: 0.19,
				price: 1080,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '9000',
				max_zipcode: '9999',
				min_running: 0,
				max_running: 0.19,
				price: 700,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '1000',
				max_zipcode: '3699',
				min_running: 0.20,
				max_running: 0.39,
				price: 505,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '3700',
				max_zipcode: '3999',
				min_running: 0.20,
				max_running: 0.39,
				price: 1765,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '4000',
				max_zipcode: '4799',
				min_running: 0.20,
				max_running: 0.39,
				price: 515,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '4800',
				max_zipcode: '4999',
				min_running: 0.20,
				max_running: 0.39,
				price: 560,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '5000',
				max_zipcode: '5999',
				min_running: 0.20,
				max_running: 0.39,
				price: 600,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '6000',
				max_zipcode: '7399',
				min_running: 0.20,
				max_running: 0.39,
				price: 650,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '7400',
				max_zipcode: '8999',
				min_running: 0.20,
				max_running: 0.39,
				price: 775,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '9000',
				max_zipcode: '9999',
				min_running: 0.20,
				max_running: 0.39,
				price: 850,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '1000',
				max_zipcode: '3699',
				min_running: 0.40,
				max_running: 0.79,
				price: 400,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '3700',
				max_zipcode: '3999',
				min_running: 0.40,
				max_running: 0.79,
				price: 1355,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '4000',
				max_zipcode: '4799',
				min_running: 0.40,
				max_running: 0.79,
				price: 412,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '4800',
				max_zipcode: '4999',
				min_running: 0.40,
				max_running: 0.79,
				price: 450,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '5000',
				max_zipcode: '5999',
				min_running: 0.40,
				max_running: 0.79,
				price: 482,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '6000',
				max_zipcode: '7399',
				min_running: 0.40,
				max_running: 0.79,
				price: 520,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '7400',
				max_zipcode: '8999',
				min_running: 0.40,
				max_running: 0.79,
				price: 623,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '9000',
				max_zipcode: '9999',
				min_running: 0.40,
				max_running: 0.79,
				price: 690,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '1000',
				max_zipcode: '3699',
				min_running: 0.80,
				max_running: 1.19,
				price: 365,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '3700',
				max_zipcode: '3999',
				min_running: 0.80,
				max_running: 1.19,
				price: 1355,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '4000',
				max_zipcode: '4799',
				min_running: 0.80,
				max_running: 1.19,
				price: 378,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '4800',
				max_zipcode: '4999',
				min_running: 0.80,
				max_running: 1.19,
				price: 405,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '5000',
				max_zipcode: '5999',
				min_running: 0.80,
				max_running: 1.19,
				price: 428,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '6000',
				max_zipcode: '7399',
				min_running: 0.80,
				max_running: 1.19,
				price: 470,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '7400',
				max_zipcode: '8999',
				min_running: 0.80,
				max_running: 1.19,
				price: 563,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '9000',
				max_zipcode: '9999',
				min_running: 0.80,
				max_running: 1.19,
				price: 620,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				max_zipcode: '3699',
				min_zipcode: '1000',
				min_running: 1.20,
				max_running: 1.59,
				price: 348,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '3700',
				max_zipcode: '3999',
				min_running: 1.20,
				max_running: 1.59,
				price: 1355,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '4000',
				max_zipcode: '4799',
				min_running: 1.20,
				max_running: 1.59,
				price: 358,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '4800',
				max_zipcode: '4999',
				min_running: 1.20,
				max_running: 1.59,
				price: 385,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '5000',
				max_zipcode: '5999',
				min_running: 1.20,
				max_running: 1.59,
				price: 408,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '6000',
				max_zipcode: '7399',
				min_running: 1.20,
				max_running: 1.59,
				price: 440,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '7400',
				max_zipcode: '8999',
				min_running: 1.20,
				max_running: 1.59,
				price: 533,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '9000',
				max_zipcode: '9999',
				min_running: 1.20,
				max_running: 1.59,
				price: 580,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				max_zipcode: '3699',
				min_zipcode: '1000',
				min_running: 1.60,
				max_running: 2.39,
				price: 327,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '3700',
				max_zipcode: '3999',
				min_running: 1.60,
				max_running: 2.39,
				price: 1355,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '4000',
				max_zipcode: '4799',
				min_running: 1.60,
				max_running: 2.39,
				price: 337.50,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '4800',
				max_zipcode: '4999',
				min_running: 1.60,
				max_running: 2.39,
				price: 362.50,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '5000',
				max_zipcode: '5999',
				min_running: 1.60,
				max_running: 2.39,
				price: 385,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '6000',
				max_zipcode: '7399',
				min_running: 1.60,
				max_running: 2.39,
				price: 415,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '7400',
				max_zipcode: '8999',
				min_running: 1.60,
				max_running: 2.39,
				price: 505,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '9000',
				max_zipcode: '9999',
				min_running: 1.60,
				max_running: 2.39,
				price: 550,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				max_zipcode: '3699',
				min_zipcode: '1000',
				min_running: 2.40,
				max_running: 3.19,
				price: 295,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '3700',
				max_zipcode: '3999',
				min_running: 2.40,
				max_running: 3.19,
				price: 1355,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '4000',
				max_zipcode: '4799',
				min_running: 2.40,
				max_running: 3.19,
				price: 302.50,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '4800',
				max_zipcode: '4999',
				min_running: 2.40,
				max_running: 3.19,
				price: 345,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '5000',
				max_zipcode: '5999',
				min_running: 2.40,
				max_running: 3.19,
				price: 367.50,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '6000',
				max_zipcode: '7399',
				min_running: 2.40,
				max_running: 3.19,
				price: 392.50,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '7400',
				max_zipcode: '8999',
				min_running: 2.40,
				max_running: 3.19,
				price: 480,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '9000',
				max_zipcode: '9999',
				min_running: 2.40,
				max_running: 3.19,
				price: 525,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				max_zipcode: '3699',
				min_zipcode: '1000',
				min_running: 3.20,
				max_running: 4.39,
				price: 262.50,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '3700',
				max_zipcode: '3999',
				min_running: 3.20,
				max_running: 4.39,
				price: 1355,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '4000',
				max_zipcode: '4799',
				min_running: 3.20,
				max_running: 4.39,
				price: 270,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '4800',
				max_zipcode: '4999',
				min_running: 3.20,
				max_running: 4.39,
				price: 290,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '5000',
				max_zipcode: '5999',
				min_running: 3.20,
				max_running: 4.39,
				price: 355,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '6000',
				max_zipcode: '7399',
				min_running: 3.20,
				max_running: 4.39,
				price: 370,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '7400',
				max_zipcode: '8999',
				min_running: 3.20,
				max_running: 4.39,
				price: 450,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '9000',
				max_zipcode: '9999',
				min_running: 3.20,
				max_running: 4.39,
				price: 500,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				max_zipcode: '3699',
				min_zipcode: '1000',
				min_running: 4.40,
				max_running: 6.39,
				price: 235,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '3700',
				max_zipcode: '3999',
				min_running: 4.40,
				max_running: 6.39,
				price: 1355,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '4000',
				max_zipcode: '4799',
				min_running: 4.40,
				max_running: 6.39,
				price: 242.50,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '4800',
				max_zipcode: '4999',
				min_running: 4.40,
				max_running: 6.39,
				price: 257.50,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '5000',
				max_zipcode: '5999',
				min_running: 4.40,
				max_running: 6.39,
				price: 340,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '6000',
				max_zipcode: '7399',
				min_running: 4.40,
				max_running: 6.39,
				price: 352.50,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '7400',
				max_zipcode: '8999',
				min_running: 4.40,
				max_running: 6.39,
				price: 422.50,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '9000',
				max_zipcode: '9999',
				min_running: 4.40,
				max_running: 6.39,
				price: 470,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				max_zipcode: '3699',
				min_zipcode: '1000',
				min_running: 6.40,
				max_running: 9.99,
				price: 200,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '3700',
				max_zipcode: '3999',
				min_running: 6.40,
				max_running: 9.99,
				price: 1355,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '4000',
				max_zipcode: '4799',
				min_running: 6.40,
				max_running: 9.99,
				price: 205,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '4800',
				max_zipcode: '4999',
				min_running: 6.40,
				max_running: 9.99,
				price: 217.50,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '5000',
				max_zipcode: '5999',
				min_running: 6.40,
				max_running: 9.99,
				price: 310,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '6000',
				max_zipcode: '7399',
				min_running: 6.40,
				max_running: 9.99,
				price: 310,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '7400',
				max_zipcode: '8999',
				min_running: 6.40,
				max_running: 9.99,
				price: 382.50,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '9000',
				max_zipcode: '9999',
				min_running: 6.40,
				max_running: 9.99,
				price: 417.50,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				max_zipcode: '3699',
				min_zipcode: '1000',
				min_running: 10,
				max_running: 11.99,
				price: 162.50,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '3700',
				max_zipcode: '3999',
				min_running: 10,
				max_running: 11.99,
				price: 1355,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '4000',
				max_zipcode: '4799',
				min_running: 10,
				max_running: 11.99,
				price: 170,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '4800',
				max_zipcode: '4999',
				min_running: 10,
				max_running: 11.99,
				price: 180,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '5000',
				max_zipcode: '5999',
				min_running: 10,
				max_running: 11.99,
				price: 257.50,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '6000',
				max_zipcode: '7399',
				min_running: 10,
				max_running: 11.99,
				price: 262.50,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '7400',
				max_zipcode: '8999',
				min_running: 10,
				max_running: 11.99,
				price: 310,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '9000',
				max_zipcode: '9999',
				min_running: 10,
				max_running: 11.99,
				price: 347.50,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				max_zipcode: '3699',
				min_zipcode: '1000',
				min_running: 12,
				max_running: 13.60,
				price: 142.50,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '3700',
				max_zipcode: '3999',
				min_running: 12,
				max_running: 13.60,
				price: 1355,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '4000',
				max_zipcode: '4799',
				min_running: 12,
				max_running: 13.60,
				price: 147.50,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '4800',
				max_zipcode: '4999',
				min_running: 12,
				max_running: 13.60,
				price: 157.50,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '5000',
				max_zipcode: '5999',
				min_running: 12,
				max_running: 13.60,
				price: 235.50,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '6000',
				max_zipcode: '7399',
				min_running: 12,
				max_running: 13.60,
				price: 250,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '7400',
				max_zipcode: '8999',
				min_running: 12,
				max_running: 13.60,
				price: 300,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '9000',
				max_zipcode: '9999',
				min_running: 12,
				max_running: 13.60,
				price: 335,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '10000',
				max_zipcode: '19999',
				min_running: 0,
				max_running: 0.19,
				price: 1940,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '20000',
				max_zipcode: '27999',
				min_running: 0,
				max_running: 0.19,
				price: 710,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '28000',
				max_zipcode: '39999',
				min_running: 0,
				max_running: 0.19,
				price: 940,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '40000',
				max_zipcode: '51999',
				min_running: 0,
				max_running: 0.19,
				price: 1070,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '52000',
				max_zipcode: '57999',
				min_running: 0,
				max_running: 0.19,
				price: 1090,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '58000',
				max_zipcode: '61999',
				min_running: 0,
				max_running: 0.19,
				price: 1170,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '62000',
				max_zipcode: '62999',
				min_running: 0,
				max_running: 0.19,
				price: 3870,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '63000',
				max_zipcode: '76999',
				min_running: 0,
				max_running: 0.19,
				price: 1950,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '77000',
				max_zipcode: '82999',
				min_running: 0,
				max_running: 0.19,
				price: 2300,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '83000',
				max_zipcode: '88999',
				min_running: 0,
				max_running: 0.19,
				price: 2750,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '89000',
				max_zipcode: '93999',
				min_running: 0,
				max_running: 0.19,
				price: 3430,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '94000',
				max_zipcode: '98999',
				min_running: 0,
				max_running: 0.19,
				price: 5160,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '10000',
				max_zipcode: '19999',
				min_running: 0.20,
				max_running: 0.39,
				price: 1580,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '20000',
				max_zipcode: '27999',
				min_running: 0.20,
				max_running: 0.39,
				price: 580,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '28000',
				max_zipcode: '39999',
				min_running: 0.20,
				max_running: 0.39,
				price: 760,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '40000',
				max_zipcode: '51999',
				min_running: 0.20,
				max_running: 0.39,
				price: 865,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '52000',
				max_zipcode: '57999',
				min_running: 0.20,
				max_running: 0.39,
				price: 885,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '58000',
				max_zipcode: '61999',
				min_running: 0.20,
				max_running: 0.39,
				price: 950,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '62000',
				max_zipcode: '62999',
				min_running: 0.20,
				max_running: 0.39,
				price: 3145,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '63000',
				max_zipcode: '76999',
				min_running: 0.20,
				max_running: 0.39,
				price: 1580,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '77000',
				max_zipcode: '82999',
				min_running: 0.20,
				max_running: 0.39,
				price: 1870,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '83000',
				max_zipcode: '88999',
				min_running: 0.20,
				max_running: 0.39,
				price: 2230,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '89000',
				max_zipcode: '93999',
				min_running: 0.20,
				max_running: 0.39,
				price: 2785,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '94000',
				max_zipcode: '98999',
				min_running: 0.20,
				max_running: 0.39,
				price: 4195,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '10000',
				max_zipcode: '19999',
				min_running: 0.40,
				max_running: 0.59,
				price: 1215,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '20000',
				max_zipcode: '27999',
				min_running: 0.40,
				max_running: 0.59,
				price: 445,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '28000',
				max_zipcode: '39999',
				min_running: 0.40,
				max_running: 0.59,
				price: 587.50,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '40000',
				max_zipcode: '51999',
				min_running: 0.40,
				max_running: 0.59,
				price: 665,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '52000',
				max_zipcode: '57999',
				min_running: 0.40,
				max_running: 0.59,
				price: 682.50,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '58000',
				max_zipcode: '61999',
				min_running: 0.40,
				max_running: 0.59,
				price: 732.50,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '62000',
				max_zipcode: '62999',
				min_running: 0.40,
				max_running: 0.59,
				price: 2420,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '63000',
				max_zipcode: '76999',
				min_running: 0.40,
				max_running: 0.59,
				price: 1217.50,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '77000',
				max_zipcode: '82999',
				min_running: 0.40,
				max_running: 0.59,
				price: 1437.50,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '83000',
				max_zipcode: '88999',
				min_running: 0.40,
				max_running: 0.59,
				price: 1717.50,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '89000',
				max_zipcode: '93999',
				min_running: 0.40,
				max_running: 0.59,
				price: 2140,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '94000',
				max_zipcode: '98999',
				min_running: 0.40,
				max_running: 0.59,
				price: 3225,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '10000',
				max_zipcode: '19999',
				min_running: 0.60,
				max_running: 13.60,
				price: 1215,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '20000',
				max_zipcode: '27999',
				min_running: 0.60,
				max_running: 13.60,
				price: 445,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '28000',
				max_zipcode: '39999',
				min_running: 0.60,
				max_running: 13.60,
				price: 586.67,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '40000',
				max_zipcode: '51999',
				min_running: 0.60,
				max_running: 13.60,
				price: 666.67,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '52000',
				max_zipcode: '57999',
				min_running: 0.60,
				max_running: 13.60,
				price: 681.67,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '58000',
				max_zipcode: '61999',
				min_running: 0.60,
				max_running: 13.60,
				price: 731.67,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '62000',
				max_zipcode: '62999',
				min_running: 0.60,
				max_running: 13.60,
				price: 2420,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '63000',
				max_zipcode: '76999',
				min_running: 0.60,
				max_running: 13.60,
				price: 1216.67,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '77000',
				max_zipcode: '82999',
				min_running: 0.60,
				max_running: 13.60,
				price: 1436.67,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '83000',
				max_zipcode: '88999',
				min_running: 0.60,
				max_running: 13.60,
				price: 1716.67,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '89000',
				max_zipcode: '93999',
				min_running: 0.60,
				max_running: 13.60,
				price: 2141.67,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '94000',
				max_zipcode: '98999',
				min_running: 0.60,
				max_running: 13.60,
				price: 3225,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '0',
				max_zipcode: '1599',
				min_running: 0,
				max_running: 0.19,
				price: 2140,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '1600',
				max_zipcode: '2299',
				min_running: 0,
				max_running: 0.19,
				price: 2170,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '2300',
				max_zipcode: '2999',
				min_running: 0,
				max_running: 0.19,
				price: 2840,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '3000',
				max_zipcode: '3999',
				min_running: 0,
				max_running: 0.19,
				price: 2980,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '4000',
				max_zipcode: '4999',
				min_running: 0,
				max_running: 0.19,
				price: 3970,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '5000',
				max_zipcode: '5999',
				min_running: 0,
				max_running: 0.19,
				price: 4120,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '6000',
				max_zipcode: '6999',
				min_running: 0,
				max_running: 0.19,
				price: 4260,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '7000',
				max_zipcode: '7999',
				min_running: 0,
				max_running: 0.19,
				price: 3970,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '8000',
				max_zipcode: '8999',
				min_running: 0,
				max_running: 0.19,
				price: 8640,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '9000',
				max_zipcode: '9299',
				min_running: 0,
				max_running: 0.19,
				price: 9620,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '9300',
				max_zipcode: '9499',
				min_running: 0,
				max_running: 0.19,
				price: 9620,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '9500',
				max_zipcode: '9999',
				min_running: 0,
				max_running: 0.19,
				price: 11780,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '0',
				max_zipcode: '1599',
				min_running: 0.20,
				max_running: 0.39,
				price: 1740,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '1600',
				max_zipcode: '2299',
				min_running: 0.20,
				max_running: 0.39,
				price: 1760,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '2300',
				max_zipcode: '2999',
				min_running: 0.20,
				max_running: 0.39,
				price: 2310,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '3000',
				max_zipcode: '3999',
				min_running: 0.20,
				max_running: 0.39,
				price: 2420,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '4000',
				max_zipcode: '4999',
				min_running: 0.20,
				max_running: 0.39,
				price: 3230,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '5000',
				max_zipcode: '5999',
				min_running: 0.20,
				max_running: 0.39,
				price: 3345,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '6000',
				max_zipcode: '6999',
				min_running: 0.20,
				max_running: 0.39,
				price: 3460,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '7000',
				max_zipcode: '7999',
				min_running: 0.20,
				max_running: 0.39,
				price: 3230,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '8000',
				max_zipcode: '8999',
				min_running: 0.20,
				max_running: 0.39,
				price: 7020,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '9000',
				max_zipcode: '9299',
				min_running: 0.20,
				max_running: 0.39,
				price: 7815,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '9300',
				max_zipcode: '9499',
				min_running: 0.20,
				max_running: 0.39,
				price: 7815,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '9500',
				max_zipcode: '9999',
				min_running: 0.20,
				max_running: 0.39,
				price: 9575,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '0',
				max_zipcode: '1599',
				min_running: 0.40,
				max_running: 0.59,
				price: 1337.50,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '1600',
				max_zipcode: '2299',
				min_running: 0.40,
				max_running: 0.59,
				price: 1355,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '2300',
				max_zipcode: '2999',
				min_running: 0.40,
				max_running: 0.59,
				price: 1775,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '3000',
				max_zipcode: '3999',
				min_running: 0.40,
				max_running: 0.59,
				price: 1862.50,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '4000',
				max_zipcode: '4999',
				min_running: 0.40,
				max_running: 0.59,
				price: 2485,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '5000',
				max_zipcode: '5999',
				min_running: 0.40,
				max_running: 0.59,
				price: 2575,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '6000',
				max_zipcode: '6999',
				min_running: 0.40,
				max_running: 0.59,
				price: 2662.50,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '7000',
				max_zipcode: '7999',
				min_running: 0.40,
				max_running: 0.59,
				price: 2485,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '8000',
				max_zipcode: '8999',
				min_running: 0.40,
				max_running: 0.59,
				price: 5402.50,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '9000',
				max_zipcode: '9299',
				min_running: 0.40,
				max_running: 0.59,
				price: 6012.50,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '9300',
				max_zipcode: '9499',
				min_running: 0.40,
				max_running: 0.59,
				price: 6012.50,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '9500',
				max_zipcode: '9999',
				min_running: 0.40,
				max_running: 0.59,
				price: 7365,
				created_at: new Date(),
				updated_at: new Date(),
			},
			//
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '0',
				max_zipcode: '1599',
				min_running: 0.60,
				max_running: 13.60,
				price: 1336.67,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '1600',
				max_zipcode: '2299',
				min_running: 0.60,
				max_running: 13.60,
				price: 1355,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '2300',
				max_zipcode: '2999',
				min_running: 0.60,
				max_running: 13.60,
				price: 1775,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '3000',
				max_zipcode: '3999',
				min_running: 0.60,
				max_running: 13.60,
				price: 1863.33,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '4000',
				max_zipcode: '4999',
				min_running: 0.60,
				max_running: 13.60,
				price: 2483.33,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '5000',
				max_zipcode: '5999',
				min_running: 0.60,
				max_running: 13.60,
				price: 2575,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '6000',
				max_zipcode: '6999',
				min_running: 0.60,
				max_running: 13.60,
				price: 2663.33,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '7000',
				max_zipcode: '7999',
				min_running: 0.60,
				max_running: 13.60,
				price: 2483.33,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '8000',
				max_zipcode: '8999',
				min_running: 0.60,
				max_running: 13.60,
				price: 5401.67,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '9000',
				max_zipcode: '9299',
				min_running: 0.60,
				max_running: 13.60,
				price: 6013.33,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '9300',
				max_zipcode: '9499',
				min_running: 0.60,
				max_running: 13.60,
				price: 6013.33,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier: 'PDK',
				carrier_product: 'PDK_G',
				min_zipcode: '9500',
				max_zipcode: '9999',
				min_running: 0.60,
				max_running: 13.60,
				price: 7365,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'SKANLOG',
				carrier_product: 'SkanlogDK',
				min_zipcode: '1000',
				max_zipcode: '3699',
				price: 160,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'SKANLOG',
				carrier_product: 'SkanlogDK',
				min_zipcode: '4000',
				max_zipcode: '4699',
				price: 160,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier: 'SKANLOG',
				carrier_product: 'SkanlogDK',
				min_zipcode: '5000',
				max_zipcode: '9000',
				price: 215,
				created_at: new Date(),
				updated_at: new Date(),
			},
		]);
	},

	down: async (queryInterface: QueryInterface, sequelize: Sequelize) => {
		await queryInterface.bulkDelete('shipment_price', null, {});
	}
};
