import { QueryInterface, Sequelize } from 'sequelize';

export = {
	up: async (queryInterface: QueryInterface, sequelize: Sequelize) => {
		await queryInterface.bulkInsert('payment_country', [
			{
				country_id: '1',
				payment_method_id: '1',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '2',
				payment_method_id: '1',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '3',
				payment_method_id: '1',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '4',
				payment_method_id: '1',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '5',
				payment_method_id: '1',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '6',
				payment_method_id: '1',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '7',
				payment_method_id: '1',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '8',
				payment_method_id: '1',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '9',
				payment_method_id: '1',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '10',
				payment_method_id: '1',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '11',
				payment_method_id: '1',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '12',
				payment_method_id: '1',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '13',
				payment_method_id: '1',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '14',
				payment_method_id: '1',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '15',
				payment_method_id: '1',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '16',
				payment_method_id: '1',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '17',
				payment_method_id: '1',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '18',
				payment_method_id: '1',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '19',
				payment_method_id: '1',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '20',
				payment_method_id: '1',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '21',
				payment_method_id: '1',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '22',
				payment_method_id: '1',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '23',
				payment_method_id: '1',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '24',
				payment_method_id: '1',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '25',
				payment_method_id: '1',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '26',
				payment_method_id: '1',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '27',
				payment_method_id: '1',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '28',
				payment_method_id: '1',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '29',
				payment_method_id: '1',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '30',
				payment_method_id: '1',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '31',
				payment_method_id: '1',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '32',
				payment_method_id: '1',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '33',
				payment_method_id: '1',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '34',
				payment_method_id: '1',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '35',
				payment_method_id: '1',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '36',
				payment_method_id: '1',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '37',
				payment_method_id: '1',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '38',
				payment_method_id: '1',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '39',
				payment_method_id: '1',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '40',
				payment_method_id: '1',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '41',
				payment_method_id: '1',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '42',
				payment_method_id: '1',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '43',
				payment_method_id: '1',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '44',
				payment_method_id: '1',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '1',
				payment_method_id: '2',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '2',
				payment_method_id: '2',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '3',
				payment_method_id: '2',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '4',
				payment_method_id: '2',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '5',
				payment_method_id: '2',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '6',
				payment_method_id: '2',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '7',
				payment_method_id: '2',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '8',
				payment_method_id: '2',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '9',
				payment_method_id: '2',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '10',
				payment_method_id: '2',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '11',
				payment_method_id: '2',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '12',
				payment_method_id: '2',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '13',
				payment_method_id: '2',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '14',
				payment_method_id: '2',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '15',
				payment_method_id: '2',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '16',
				payment_method_id: '2',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '17',
				payment_method_id: '2',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '18',
				payment_method_id: '2',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '19',
				payment_method_id: '2',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '20',
				payment_method_id: '2',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '21',
				payment_method_id: '2',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '22',
				payment_method_id: '2',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '23',
				payment_method_id: '2',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '24',
				payment_method_id: '2',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '25',
				payment_method_id: '2',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '26',
				payment_method_id: '2',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '27',
				payment_method_id: '2',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '28',
				payment_method_id: '2',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '29',
				payment_method_id: '2',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '30',
				payment_method_id: '2',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '31',
				payment_method_id: '2',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '32',
				payment_method_id: '2',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '33',
				payment_method_id: '2',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '34',
				payment_method_id: '2',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '35',
				payment_method_id: '2',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '36',
				payment_method_id: '2',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '37',
				payment_method_id: '2',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '38',
				payment_method_id: '2',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '39',
				payment_method_id: '2',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '40',
				payment_method_id: '2',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '41',
				payment_method_id: '2',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '42',
				payment_method_id: '2',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '43',
				payment_method_id: '2',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '44',
				payment_method_id: '2',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '1',
				payment_method_id: '4',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '2',
				payment_method_id: '9',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '3',
				payment_method_id: '9',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '39',
				payment_method_id: '9',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '1',
				payment_method_id: '12',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '2',
				payment_method_id: '6',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '3',
				payment_method_id: '6',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '39',
				payment_method_id: '6',
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: '38',
				payment_method_id: '6',
				created_at: new Date(),
				updated_at: new Date(),
			},
		]);
	},

	down: async (queryInterface: QueryInterface, sequelize: Sequelize) => {
		await queryInterface.bulkDelete('payment_country', null, {});
	}
};
