import { QueryInterface, Sequelize } from 'sequelize';

export = {
	up: async (queryInterface: QueryInterface, sequelize: Sequelize) => {
		await queryInterface.bulkInsert('carrier-country-config', [
			{
				country_id: 1,
				carrier_id: 2,
				carrier_product: 'PDK_G',
				carrier_product_title: 'Postnord',
				show_pick_up: false,
				show_delivery: false,
				show_extra_service: false,
				show_extra_service_flex: true,
				sms_nt: true,
				email_nt: true,
				sms_pnt: false,
				email_pnt: false,
				flex_delivery: true,
				flex_tel_notification: true,
				private_address: true,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier_id: 4,
				carrier_product: 'SkanlogDK',
				carrier_product_title: 'Skanlog Direct',
				show_pick_up: true,
				show_delivery: true,
				show_extra_service: true,
				show_extra_service_flex: false,
				sms_nt: false,
				email_nt: false,
				sms_pnt: false,
				email_pnt: false,
				flex_delivery: false,
				flex_tel_notification: false,
				private_address: false,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier_id: 1,
				carrier_product: 'GLSDK_SD',
				carrier_product_title: 'GLS Shop Delivery',
				show_pick_up: false,
				show_delivery: false,
				show_extra_service: false,
				show_extra_service_flex: false,
				sms_nt: true,
				email_nt: true,
				sms_pnt: false,
				email_pnt: false,
				flex_delivery: false,
				flex_tel_notification: false,
				private_address: false,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier_id: 1,
				carrier_product: 'GLSDK_SR',
				carrier_product_title: 'GLS Shop Return Service',
				show_pick_up: false,
				show_delivery: false,
				show_extra_service: false,
				show_extra_service_flex: false,
				sms_nt: false,
				email_nt: false,
				sms_pnt: true,
				email_pnt: true,
				flex_delivery: false,
				flex_tel_notification: false,
				private_address: false,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier_id: 1,
				carrier_product: 'GLSDK_BP',
				carrier_product_title: 'GLS Business Parcel',
				show_pick_up: false,
				show_delivery: false,
				show_extra_service: false,
				show_extra_service_flex: true,
				sms_nt: true,
				email_nt: true,
				sms_pnt: false,
				email_pnt: false,
				flex_delivery: true,
				flex_tel_notification: false,
				private_address: false,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 1,
				carrier_id: 1,
				carrier_product: 'GLSDK_HD',
				carrier_product_title: 'GLS Private Delivery Parcel',
				show_pick_up: false,
				show_delivery: false,
				show_extra_service: false,
				show_extra_service_flex: false,
				sms_nt: true,
				email_nt: true,
				sms_pnt: false,
				email_pnt: false,
				flex_delivery: false,
				flex_tel_notification: false,
				private_address: false,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier_id: 2,
				carrier_product: 'PDK_G',
				carrier_product_title: 'Postnord',
				show_pick_up: false,
				show_delivery: false,
				show_extra_service: false,
				show_extra_service_flex: true,
				sms_nt: true,
				email_nt: true,
				sms_pnt: false,
				email_pnt: false,
				flex_delivery: true,
				flex_tel_notification: true,
				private_address: true,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier_id: 5,
				carrier_product: 'SkanlogSE',
				carrier_product_title: 'Skanlog Direct Sweden ',
				show_pick_up: false,
				show_delivery: false,
				show_extra_service: true,
				show_extra_service_flex: false,
				sms_nt: false,
				email_nt: false,
				sms_pnt: false,
				email_pnt: false,
				flex_delivery: false,
				flex_tel_notification: false,
				private_address: false,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 2,
				carrier_id: 1,
				carrier_product: 'GLSDK_EBP',
				carrier_product_title: 'GLS Euro Business Parcel',
				show_pick_up: false,
				show_delivery: false,
				show_extra_service: false,
				show_extra_service_flex: false,
				sms_nt: true,
				email_nt: true,
				sms_pnt: false,
				email_pnt: false,
				flex_delivery: false,
				flex_tel_notification: false,
				private_address: false,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 39,
				carrier_id: 1,
				carrier_product: 'GLSDK_EBP',
				carrier_product_title: 'GLS Euro Business Parcel',
				show_pick_up: false,
				show_delivery: false,
				show_extra_service: false,
				show_extra_service_flex: false,
				sms_nt: true,
				email_nt: true,
				sms_pnt: false,
				email_pnt: false,
				flex_delivery: false,
				flex_tel_notification: false,
				private_address: false,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 15,
				carrier_id: 1,
				carrier_product: 'GLSDK_EBP',
				carrier_product_title: 'GLS Euro Business Parcel',
				show_pick_up: false,
				show_delivery: false,
				show_extra_service: false,
				show_extra_service_flex: false,
				sms_nt: true,
				email_nt: true,
				sms_pnt: false,
				email_pnt: false,
				flex_delivery: false,
				flex_tel_notification: false,
				private_address: false,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 8,
				carrier_id: 1,
				carrier_product: 'GLSDK_EBP',
				carrier_product_title: 'GLS Euro Business Parcel',
				show_pick_up: false,
				show_delivery: false,
				show_extra_service: false,
				show_extra_service_flex: false,
				sms_nt: true,
				email_nt: true,
				sms_pnt: false,
				email_pnt: false,
				flex_delivery: false,
				flex_tel_notification: false,
				private_address: false,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 16,
				carrier_id: 1,
				carrier_product: 'GLSDK_EBP',
				carrier_product_title: 'GLS Euro Business Parcel',
				show_pick_up: false,
				show_delivery: false,
				show_extra_service: false,
				show_extra_service_flex: false,
				sms_nt: true,
				email_nt: true,
				sms_pnt: false,
				email_pnt: false,
				flex_delivery: false,
				flex_tel_notification: false,
				private_address: false,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 28,
				carrier_id: 1,
				carrier_product: 'GLSDK_EBP',
				carrier_product_title: 'GLS Euro Business Parcel',
				show_pick_up: false,
				show_delivery: false,
				show_extra_service: false,
				show_extra_service_flex: false,
				sms_nt: true,
				email_nt: true,
				sms_pnt: false,
				email_pnt: false,
				flex_delivery: false,
				flex_tel_notification: false,
				private_address: false,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 20,
				carrier_id: 1,
				carrier_product: 'GLSDK_EBP',
				carrier_product_title: 'GLS Euro Business Parcel',
				show_pick_up: false,
				show_delivery: false,
				show_extra_service: false,
				show_extra_service_flex: false,
				sms_nt: true,
				email_nt: true,
				sms_pnt: false,
				email_pnt: false,
				flex_delivery: false,
				flex_tel_notification: false,
				private_address: false,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 21,
				carrier_id: 1,
				carrier_product: 'GLSDK_EBP',
				carrier_product_title: 'GLS Euro Business Parcel',
				show_pick_up: false,
				show_delivery: false,
				show_extra_service: false,
				show_extra_service_flex: false,
				sms_nt: true,
				email_nt: true,
				sms_pnt: false,
				email_pnt: false,
				flex_delivery: false,
				flex_tel_notification: false,
				private_address: false,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 24,
				carrier_id: 1,
				carrier_product: 'GLSDK_EBP',
				carrier_product_title: 'GLS Euro Business Parcel',
				show_pick_up: false,
				show_delivery: false,
				show_extra_service: false,
				show_extra_service_flex: false,
				sms_nt: true,
				email_nt: true,
				sms_pnt: false,
				email_pnt: false,
				flex_delivery: false,
				flex_tel_notification: false,
				private_address: false,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 29,
				carrier_id: 1,
				carrier_product: 'GLSDK_EBP',
				carrier_product_title: 'GLS Euro Business Parcel',
				show_pick_up: false,
				show_delivery: false,
				show_extra_service: false,
				show_extra_service_flex: false,
				sms_nt: true,
				email_nt: true,
				sms_pnt: false,
				email_pnt: false,
				flex_delivery: false,
				flex_tel_notification: false,
				private_address: false,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 6,
				carrier_id: 1,
				carrier_product: 'GLSDK_EBP',
				carrier_product_title: 'GLS Euro Business Parcel',
				show_pick_up: false,
				show_delivery: false,
				show_extra_service: false,
				show_extra_service_flex: false,
				sms_nt: true,
				email_nt: true,
				sms_pnt: false,
				email_pnt: false,
				flex_delivery: false,
				flex_tel_notification: false,
				private_address: false,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 30,
				carrier_id: 1,
				carrier_product: 'GLSDK_EBP',
				carrier_product_title: 'GLS Euro Business Parcel',
				show_pick_up: false,
				show_delivery: false,
				show_extra_service: false,
				show_extra_service_flex: false,
				sms_nt: true,
				email_nt: true,
				sms_pnt: false,
				email_pnt: false,
				flex_delivery: false,
				flex_tel_notification: false,
				private_address: false,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 6,
				carrier_id: 3,
				carrier_product: 'DSV_RGE',
				carrier_product_title: 'DSV Road',
				show_pick_up: false,
				show_delivery: false,
				show_extra_service: false,
				show_extra_service_flex: true,
				sms_nt: false,
				email_nt: false,
				sms_pnt: false,
				email_pnt: false,
				flex_delivery: true,
				flex_tel_notification: false,
				private_address: false,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 38,
				carrier_id: 3,
				carrier_product: 'DSV_RGE',
				carrier_product_title: 'DSV Road',
				show_pick_up: false,
				show_delivery: false,
				show_extra_service: false,
				show_extra_service_flex: true,
				sms_nt: false,
				email_nt: false,
				sms_pnt: false,
				email_pnt: false,
				flex_delivery: true,
				flex_tel_notification: false,
				private_address: false,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 10,
				carrier_id: 3,
				carrier_product: 'DSV_RGE',
				carrier_product_title: 'DSV Road',
				show_pick_up: false,
				show_delivery: false,
				show_extra_service: false,
				show_extra_service_flex: true,
				sms_nt: false,
				email_nt: false,
				sms_pnt: false,
				email_pnt: false,
				flex_delivery: true,
				flex_tel_notification: false,
				private_address: false,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 3,
				carrier_id: 2,
				carrier_product: 'PDK_G',
				carrier_product_title: 'Postnord',
				show_pick_up: false,
				show_delivery: false,
				show_extra_service: false,
				show_extra_service_flex: true,
				sms_nt: true,
				email_nt: true,
				sms_pnt: false,
				email_pnt: false,
				flex_delivery: true,
				flex_tel_notification: true,
				private_address: true,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 8,
				carrier_id: 3,
				carrier_product: 'DSV_RGE',
				carrier_product_title: 'DSV Road',
				show_pick_up: false,
				show_delivery: false,
				show_extra_service: false,
				show_extra_service_flex: true,
				sms_nt: false,
				email_nt: false,
				sms_pnt: false,
				email_pnt: false,
				flex_delivery: true,
				flex_tel_notification: false,
				private_address: false,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 39,
				carrier_id: 3,
				carrier_product: 'DSV_RGE',
				carrier_product_title: 'DSV Road',
				show_pick_up: false,
				show_delivery: false,
				show_extra_service: false,
				show_extra_service_flex: true,
				sms_nt: false,
				email_nt: false,
				sms_pnt: false,
				email_pnt: false,
				flex_delivery: true,
				flex_tel_notification: false,
				private_address: false,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 14,
				carrier_id: 3,
				carrier_product: 'DSV_RGE',
				carrier_product_title: 'DSV Road',
				show_pick_up: false,
				show_delivery: false,
				show_extra_service: false,
				show_extra_service_flex: true,
				sms_nt: false,
				email_nt: false,
				sms_pnt: false,
				email_pnt: false,
				flex_delivery: true,
				flex_tel_notification: false,
				private_address: false,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 16,
				carrier_id: 3,
				carrier_product: 'DSV_RGE',
				carrier_product_title: 'DSV Road',
				show_pick_up: false,
				show_delivery: false,
				show_extra_service: false,
				show_extra_service_flex: true,
				sms_nt: false,
				email_nt: false,
				sms_pnt: false,
				email_pnt: false,
				flex_delivery: true,
				flex_tel_notification: false,
				private_address: false,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 17,
				carrier_id: 3,
				carrier_product: 'DSV_RGE',
				carrier_product_title: 'DSV Road',
				show_pick_up: false,
				show_delivery: false,
				show_extra_service: false,
				show_extra_service_flex: true,
				sms_nt: false,
				email_nt: false,
				sms_pnt: false,
				email_pnt: false,
				flex_delivery: true,
				flex_tel_notification: false,
				private_address: false,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 21,
				carrier_id: 3,
				carrier_product: 'DSV_RGE',
				carrier_product_title: 'DSV Road',
				show_pick_up: false,
				show_delivery: false,
				show_extra_service: false,
				show_extra_service_flex: true,
				sms_nt: false,
				email_nt: false,
				sms_pnt: false,
				email_pnt: false,
				flex_delivery: true,
				flex_tel_notification: false,
				private_address: false,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 28,
				carrier_id: 3,
				carrier_product: 'DSV_RGE',
				carrier_product_title: 'DSV Road',
				show_pick_up: false,
				show_delivery: false,
				show_extra_service: false,
				show_extra_service_flex: true,
				sms_nt: false,
				email_nt: false,
				sms_pnt: false,
				email_pnt: false,
				flex_delivery: true,
				flex_tel_notification: false,
				private_address: false,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 29,
				carrier_id: 3,
				carrier_product: 'DSV_RGE',
				carrier_product_title: 'DSV Road',
				show_pick_up: false,
				show_delivery: false,
				show_extra_service: false,
				show_extra_service_flex: true,
				sms_nt: false,
				email_nt: false,
				sms_pnt: false,
				email_pnt: false,
				flex_delivery: true,
				flex_tel_notification: false,
				private_address: false,
				created_at: new Date(),
				updated_at: new Date(),
			},
			{
				country_id: 30,
				carrier_id: 3,
				carrier_product: 'DSV_RGE',
				carrier_product_title: 'DSV Road',
				show_pick_up: false,
				show_delivery: false,
				show_extra_service: false,
				show_extra_service_flex: true,
				sms_nt: false,
				email_nt: false,
				sms_pnt: false,
				email_pnt: false,
				flex_delivery: true,
				flex_tel_notification: false,
				private_address: false,
				created_at: new Date(),
				updated_at: new Date(),
			},
		]);
	},

	down: async (queryInterface: QueryInterface, sequelize: Sequelize) => {
		await queryInterface.bulkDelete('carrier-country-config', null, {});
	}
};
